//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPeriodicTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserName
    {
        public int UserID { get; set; }
        public string UserNickName { get; set; }
        public Nullable<int> UserScore { get; set; }
    }
}
